# Generated by Django 5.0.6 on 2024-07-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(default=False)),
                ('last_ping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
